services:
  - type: web
    name: kijangwan-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate && gunicorn config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://kijangwan-backend.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://kijangwan-frontend.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: kijangwan-db
          property: connectionString

  - type: web
    name: kijangwan-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: kijangwan-db
